[package]
name = "rarb"
version = "0.1.0"
authors = ["David Holtz <David.richard.holtz@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.2", features = ["serde"] }
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
time = "*"